import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import { Toaster } from "react-hot-toast";
import AppLayout from "@/components/shared/Applayout";
import SocketProvider from "@/components/SocketProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AnyOne Can Connect",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/LOGOANY.png" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <SocketProvider/>
          <Toaster />
          <AppLayout>
            {children}
          </AppLayout>
          
        </ReduxProvider>
      </body>
    </html>
  );
}
